package it.unive.lisa.symbolic.value;

public enum BinaryOperator {
	NUMERIC_SUB, NUMERIC_ADD, NUMERIC_DIV, NUMERIC_MUL, NUMERIC_MOD,

	LOGICAL_OR, LOGICAL_AND,

	COMPARISON_NE, COMPARISON_EQ, COMPARISON_GE, COMPARISON_GT, COMPARISON_LE, COMPARISON_LT
}
