package it.unive.lisa;

import static org.junit.Assert.fail;

import it.unive.lisa.outputs.serializableGraph.SerializableGraph;
import it.unive.lisa.util.file.FileManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Paths;
import org.junit.Ignore;
import org.junit.Test;

public class CronUtils {

	@Test
	@Ignore("This is just an utility to visualize the json graphs generated by the test system")
	public void generateFromJson() throws IOException {
		String target = "test-outputs/numeric/sign/untyped_tutorial.sign_parity_example(tutorial__this).json";

		File throwAway = Paths.get(AnalysisTestExecutor.ACTUAL_RESULTS_DIR, "throw-away").toFile();
		try {
			FileManager.forceDeleteFolder(throwAway.toString());
			throwAway.mkdirs();
		} catch (IOException e) {
			e.printStackTrace(System.err);
			fail("Cannot delete working directory '" + throwAway + "': " + e.getMessage());
		}

		FileManager mgr = new FileManager(throwAway.toString());

		File tg = new File(target);
		try (Reader r = new InputStreamReader(new FileInputStream(tg), StandardCharsets.UTF_8)) {
			SerializableGraph graph = SerializableGraph.readGraph(r);
			mgr.mkHtmlFile("generated", ww -> graph.toHtml(true, target).dump(ww));
			mgr.usedHtmlViewer();
			mgr.generateSupportFiles();
		}
	}
}
